services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - ../.env.global
    environment:
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    ports:
      - 8081:80
    volumes:
      - ../../config/security/vaultwarden:/data
    networks:
      - homelab-net

networks:
  homelab-net:
    external: true
