services:
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    restart: unless-stopped
    env_file:
      - ../.env.global
    ports:
      - 6800:6800
      - 6888:6888
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - RPC_SECRET=${ARIA2_RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
    volumes:
      - ../../config/downloader/aria2:/config
      - ../../data/downloads:/downloads

  ariang:
    image: p3terx/ariang
    container_name: ariang
    restart: unless-stopped
    ports:
      - 6880:6880
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      - aria2

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - WEBUI_PORT=8085
    ports:
      - 8085:8085 # WebUI
      - 6881:6881 # Torrent TCP
      - 6881:6881/udp # Torrent UDP
    volumes:
      - ../../config/downloader/qbittorrent:/config
      - ../../data/downloads:/downloads


networks:
  default:
    name: homelab-net
    external: true
